



setwd("/home/gerald/Documentos/Clases_propias/genomica_con_linuxR/roary/roary")
getwd()

# Read the presence/absence matrix obtained from Roary
# Cargar el archivo de texto separado por tabulaciones correctamente

###########################
##Pangenomica descriptiva##
###########################

library(data.table)
data <- fread("gene_presence_absence.Rtab", sep = "\t", header = TRUE, check.names = FALSE)

class(data)

data <- data[,-1]

# Calculate pangenome size
pangenome_size = nrow(data)
# Calculate the core, shell and cloud sizes as assigned by panaroo
core_size <- length(rowSums(data)[rowSums(data) >= 0.99*ncol(data)])
shell_size <- length(rowSums(data)[rowSums(data) < 0.99*ncol(data) &
                                     rowSums(data) > 0.15*ncol(data)])
cloud_size <- length(rowSums(data)[rowSums(data) <= 0.15*ncol(data)])
par(mfrow = c(1, 2),pin = c(2.5, 2.5))
# Plot a pie chart displaying the core and accessory proportions; this is
slices <- c(core_size,shell_size,cloud_size)
pct <- round(slices/sum(slices)*100,2)
lab <- paste(c("core", "shell", "cloud"),pct,"%",sep=" ")
pie(slices, labels = lab, main="Pangenome", cex=0.8)

# Plot a histogram of genes families in the 14 S. Typhimurium genomes;
hist(rowSums(data), xlab = "Number of genomes containing a gene",
     ylab = "Number of genes", main = "Gene frequency",
     ylim = c(0,5000), xlim = c(0,ncol(data)+1),
     breaks = seq(min(rowSums(data))-0.5, max(rowSums(data))+0.5, by = 1))


devtools::install_github("larssnip/micropan")
library(micropan)
data <- read.table("gene_presence_absence.Rtab", sep = "\t",
                   header = T, row.names = 1, check.names = F)


###########################################################

#####################
##Diagramas de Venn##
#####################
install.packages("BiocManager")
BiocManager::install("limma")
library(limma)
# select only four genomes from the dataset
counts <- vennCounts(data[1:4126, 1:6])
# plot Venn diagram
vennDiagram(counts, circle.col = c("red", "blue", "green3", "yellow"), cex =1)

###########################################################

###########
##Heatmap##
###########

library(pheatmap)
# read presence/absence matrix of gene content from panaroo
data <- read.table("gene_presence_absence.Rtab",sep = "\t",header = T,
                   row.names = 1, check.names = F)
# transpose dataframe
df_t <- t(data)
rownames(df_t) <- colnames(data)
colnames(df_t) <- rownames(data)
# convert dataframe to matrix
pange <- as.matrix(df_t, as.numeric)
rownames(pange) <- colnames(data)
# plot heatmap showed in Figurer 4A
hm <- pheatmap(pange, clustering_distance_rows = "manhattan",
               clustering_method = "ward.D", color = c("white", "skyblue4"),
               clustering_distance_cols = "manhattan", show_colnames = F,
               cluster_cols = T, cluster_rows = T, legend = F)
# recover data matrix from heatmap after clustering
reorder <- data[hm$tree_col[["order"]],]
reorder <- reorder[,hm$tree_row[["order"]]]

# plot heatmap of a selected region of the pangenome matrix
p2 <- pheatmap(t(reorder[5816:5890,]), show_colnames = T,
               cluster_cols = F, cluster_rows = F, legend = F,
               color = c("white", "skyblue4"))



###############################################################################
#Este codigo que esta a continuacion me genera analisis PCA 
#######
##PCA##
#######

setwd("/home/gerald/Documentos/Clases_propias/genomica_con_linuxR/roary/roary")

library(ggplot2)
# read the presence/absence matrix generated by panaroo
data <- fread("gene_presence_absence.Rtab", sep = "\t", header = TRUE, check.names = FALSE)

#Esta parte correr linea por linea cuidadosamente
# transpose dataframe
df_t <- t(data)
df_new <- df_t[-1,] 
colnames(df_t)
rownames(df_t)
colnames(df_t) <- data[["Gene"]]
df_t <- df_t[-1,]

df_t1 <- df_t
df_t1 <- as.data.frame(df_t1)
# Crear una nueva columna con la primera parte del nombre hasta el segundo guion bajo
df_t1$Assembly<- sapply(rownames(df_t1), function(x) {
  parts <- unlist(strsplit(x, "_"))  # Dividir el nombre por "_"
  paste(parts[1], parts[2], sep = "_")  # Combinar la primera y segunda parte
})

# read the metadata (table 1 of this chapter) as a dataframe
meta <- read.csv("metadata.csv", header = T, sep = ",")

#Arreglando datos

str(df_t1["Assembly"])
str(meta["Assembly"])


# memeta# merge presence/absence matrix with metadata into one dataframe
dafr <- data.frame(merge(df_t1, meta, by = "Assembly"))

# Función para identificar si una columna contiene solo "0" o "1"
is_binary_character <- function(column) {
  all(column %in% c("0", "1"))
}

# Aplicar la conversión solo a las columnas que contienen exclusivamente "0" y "1"
dafr[] <- lapply(dafr, function(column) {
  if (is_binary_character(column)) {
    as.integer(column)  # Convertir a entero si es binario
  } else {
    column  # Dejar la columna intacta si contiene otros caracteres
  }
})




# compute principal components on the accessory portion of the pangenome
PC<-prcomp(dafr[, c(2:4100)])
# you can use "Country" instead of "Host"
#PCi<-data.frame(PC$x, Host=dafr$Host)
PCi<-data.frame(PC$x, Host=dafr$Host)
# plot PCA labeled by Host (or Phylogroup)
ggplot(PCi, aes(x=PC1,y=PC2,fill=Host)) +
  geom_point(size = 5, alpha = 0.5, shape = 21) +
  scale_fill_brewer(palette = "Set1") +
  theme_bw()

